// Language Translations
const translations = {
    en: {
        tagline: "MULTIDISCIPLINARY LANGUAGE PROFESSIONAL",
        nav_home: "Home",
        nav_about: "Summary",
        nav_portfolio: "Portfolio",
        nav_consultancy: "Consultancy",
        hero_greeting: "Welcome, I'm",
        hero_desc: "Multilingual contract & localization specialist with expertise in legal international documentation, cross-border publishing and multilingual administrative coordination.",
        btn_portfolio: "Portfolio",
        btn_resume: "Resume",
        title_about: "SUMMARY",
        about_administration_title: "Administration",
        about_administration_desc: "Experience in multilingual administrative coordination, supporting cross-border communication, intermediary documentation processes and maintaining terminological consistency across international operations.",
        about_automation_title: "Automation",
        about_automation_desc: "Design and implementation of structured automation systems aimed at reducing manual workload and improving efficiency in administrative and documentation processes within multilingual environments.",
        about_contract_engineering_title: "Contract Engineering",
        about_contract_engineering_desc: "Development and refinement of multilingual contractual structures for cross-border agreements, with emphasis on clarity, enforceability and consistency across different jurisdictions.",
        about_localization_title: "Localization",
        about_localization_desc: "Adaptation and localization of legal, administrative and publishing documentation for international and national contexts, ensuring linguistic accuracy and cultural coherence.",
        about_multichannel_operations_title: "Multichannel Operations",
        about_multichannel_operations_desc: "Coordination of content publication across multiple digital channels, ensuring consistent deployment and specific adaptations while applying multichannel localization where required.",
        about_sales_operations_title: "Sales Operations",
        about_sales_operations_desc: "Management of structured sales funnels, invoice workflows and direct sales communication to support secure transactions and efficient client onboarding.",
        title_portfolio: "PORTFOLIO",
        title_languages: "LANGUAGES",
        badge_holding: "Holding Agency",
        grape_desc: "GrapeXagon is an emerging holding agency designed to develop and coordinate interconnected digital platforms, establishing the operational, structural, and strategic framework for scalable online ventures.",
        btn_learn_more: "Learn More",
        title_consultancy: "CONSULTANCY",
        consultancy_desc: "Looking for expertise in contract engineering, localization or workflow automation? Propose a deal:",
        form_company_check: "Company?",
        form_name: "Name",
        form_surname: "Surname",
        form_company_name: "Company's Name",
        form_email: "E-mail",
        form_phone_check: "Include number?",
        form_phone: "Phone Number",
        form_phone_error: "Please enter a valid phone number.",
        form_message: "Proposal",
        form_submit: "Send Proposal",
        form_sending: "Sending...",
        form_success: "Proposal sent successfully!",
        form_error: "Please fill in all required fields with valid information.",
        form_error_required: "Please fill in all required fields with valid information.",
        form_error_captcha: "Please complete the reCAPTCHA verification.",
        footer_phone: "Number",
        footer_email: "E-mail",
        footer_follow: "LinkedIn",
        footer_rights: "by Delta N. Asterling A. F."
    },
    ca: {
        tagline: "PROFESSIONAL LINGÜÍSTIC MULTIDISCIPLINAR",
        nav_home: "Inici",
        nav_about: "Resum",
        nav_portfolio: "Portafoli",
        nav_consultancy: "Consultoria",
        hero_greeting: "Benvinguda, sóc",
        hero_desc: "Especialista en contractes i localització multilingüe amb experiència en documentació legal internacional, publicació transfronterera i coordinació administrativa multilingüe.",
        btn_portfolio: "Portafoli",
        btn_resume: "Currículum",
        title_about: "RESUM",
        about_administration_title: "Administració",
        about_administration_desc: "Experiència en coordinació administrativa multilingüe, suport a la comunicació transfronterera, processos de documentació intermedis i manteniment de la consistència terminològica en operacions internacionals.",
        about_automation_title: "Automatització",
        about_automation_desc: "Disseny i implementació de sistemes d'automatització estructurats orientats a reduir la càrrega de treball manual i millorar l'eficiència en processos administratius i de documentació en entorns multilingües.",
        about_contract_engineering_title: "Enginyeria de Contractes",
        about_contract_engineering_desc: "Desenvolupament i refinament d'estructures contractuals multilingües per a acords transfronterers, amb èmfasi en la claredat, exigibilitat i consistència entre diferents jurisdiccions.",
        about_localization_title: "Localització",
        about_localization_desc: "Adaptació i localització de documentació legal, administrativa i editorial per a contextos internacionals i nacionals, assegurant precisió lingüística i coherència cultural.",
        about_multichannel_operations_title: "Operacions Multicanal",
        about_multichannel_operations_desc: "Coordinació de la publicació de continguts a través de múltiples canals digitals, assegurant el desplegament consistent i adaptacions específiques aplicant localització multicanal quan sigui necessari.",
        about_sales_operations_title: "Operacions de Vendes",
        about_sales_operations_desc: "Gestió d'embutits de vendes estructurats, fluxos de treball de facturació i comunicació directa de vendes per a suportar transaccions segures i una incorporació eficient de clients.",
        title_portfolio: "PORTAFOLI",
        title_languages: "IDIOMES",
        badge_holding: "Agència Holding",
        grape_desc: "GrapeXagon és una agència holding emergent dissenyada per desenvolupar i coordinar plataformes digitals interconnectades, establint el marc operatiu, estructural i estratègic per a empreses en línia escalables.",
        btn_learn_more: "Saber-ne més",
        title_consultancy: "CONSULTORIA",
        consultancy_desc: "Busques experiència en enginyeria de contractes, localització o automatització de fluxos de treball? Proposa un tracte:",
        form_company_check: "Empresa?",
        form_name: "Nom",
        form_surname: "Cognom",
        form_company_name: "Nom de l'empresa",
        form_email: "Correu electrònic",
        form_phone_check: "Incloure número?",
        form_phone: "Número de telèfon",
        form_phone_error: "Introduïu un número de telèfon vàlid.",
        form_message: "Proposta",
        form_submit: "Enviar proposta",
        form_sending: "Enviant...",
        form_success: "Proposta enviada amb èxit!",
        form_error: "Si us plau, ompli tots els camps obligatoris amb informació vàlida.",
        form_error_required: "Si us plau, ompli tots els camps obligatoris amb informació vàlida.",
        form_error_captcha: "Si us plau, completeu la verificació reCAPTCHA.",
        footer_phone: "Telèfon",
        footer_email: "Correu electrònic",
        footer_follow: "LinkedIn",
        footer_rights: "per Delta N. Asterling A. F."
    },
    es: {
        tagline: "PROFESIONAL LINGÜÍSTICO MULTIDISCIPLINARIO",
        nav_home: "Inicio",
        nav_about: "Resumen",
        nav_portfolio: "Portafolio",
        nav_consultancy: "Consultoría",
        hero_greeting: "Bienvenido, soy",
        hero_desc: "Especialista en contratos y localización multilingüe con experiencia en documentación legal internacional, edición transfronteriza y coordinación administrativa multilingüe.",
        btn_portfolio: "Portafolio",
        btn_resume: "Currículum",
        title_about: "RESUMEN",
        about_administration_title: "Administración",
        about_administration_desc: "Experiencia en coordinación administrativa multilingüe, apoyo a la comunicación transfronteriza, procesos de documentación intermediaria y mantenimiento de la consistencia terminológica en operaciones internacionales.",
        about_automation_title: "Automatización",
        about_automation_desc: "Diseño e implementación de sistemas de automatización estructurados orientados a reducir la carga de trabajo manual y mejorar la eficiencia en procesos administrativos y de documentación en entornos multilingües.",
        about_contract_engineering_title: "Ingeniería de Contratos",
        about_contract_engineering_desc: "Desarrollo y refinamiento de estructuras contractuales multilingües para acuerdos transfronterizos, con énfasis en la claridad, exigibilidad y consistencia entre diferentes jurisdicciones.",
        about_localization_title: "Localización",
        about_localization_desc: "Adaptación y localización de documentación legal, administrativa y editorial para contextos internacionales y nacionales, asegurando precisión lingüística y coherencia cultural.",
        about_multichannel_operations_title: "Operaciones Multicanal",
        about_multichannel_operations_desc: "Coordinación de la publicación de contenidos a través de múltiples canales digitales, asegurando el despliegue consistente y adaptaciones específicas, aplicando localización multicanal cuando sea necesario.",
        about_sales_operations_title: "Operaciones de Ventas",
        about_sales_operations_desc: "Gestión de embudos de ventas estructurados, flujos de trabajo de facturación y comunicación directa de ventas para apoyar transacciones seguras y una incorporación eficiente de clientes.",
        title_portfolio: "PORTAFOLIO",
        title_languages: "IDIOMAS",
        badge_holding: "Agencia Holding",
        grape_desc: "GrapeXagon es una agencia holding emergente diseñada para desarrollar y coordinar plataformas digitales interconectadas, estableciendo el marco operativo, estructural y estratégico para empresas en línea escalables.",
        btn_learn_more: "Saber Más",
        title_consultancy: "CONSULTORÍA",
        consultancy_desc: "¿Busca experiencia en ingeniería de contratos, localización o automatización de flujos de trabajo? Proponga un trato:",
        form_company_check: "¿Empresa?",
        form_name: "Nombre",
        form_surname: "Apellido",
        form_company_name: "Nombre de la empresa",
        form_email: "Correo electrónico",
        form_phone_check: "¿Incluir número?",
        form_phone: "Número de teléfono",
        form_phone_error: "Por favor, ingrese un número de teléfono válido.",
        form_message: "Propuesta",
        form_submit: "Enviar propuesta",
        form_sending: "Enviando...",
        form_success: "¡Propuesta enviada con éxito!",
        form_error: "Por favor, complete todos los campos obligatorios con información válida.",
        form_error_required: "Por favor, complete todos los campos obligatorios con información válida.",
        form_error_captcha: "Por favor, complete la verificación reCAPTCHA.",
        footer_phone: "Teléfono",
        footer_email: "Correo electrónico",
        footer_follow: "LinkedIn",
        footer_rights: "por Delta N. Asterling A. F."
    },
    fr: {
        tagline: "PROFESSIONNEL LINGUISTIQUE MULTIDISCIPLINAIRE",
        nav_home: "Accueil",
        nav_about: "Résumé",
        nav_portfolio: "Portfolio",
        nav_consultancy: "Consultation",
        hero_greeting: "Bienvenue, je suis",
        hero_desc: "Spécialiste multilingue des contrats et de la localisation avec expertise en documentation juridique internationale, édition transfrontalière et coordination administrative multilingue.",
        btn_portfolio: "Portfolio",
        btn_resume: "CV",
        title_about: "RÉSUMÉ",
        about_administration_title: "Administration",
        about_administration_desc: "Expérience en coordination administrative multilingue, soutien à la communication transfrontalière, processus de documentation intermédiaire et maintien de la cohérence terminologique dans les opérations internationales.",
        about_automation_title: "Automatisation",
        about_automation_desc: "Conception et mise en œuvre de systèmes d'automatisation structurés visant à réduire la charge de travail manuel et à améliorer l'efficacité des processus administratifs et documentaires dans des environnements multilingues.",
        about_contract_engineering_title: "Ingénierie Contractuelle",
        about_contract_engineering_desc: "Développement et affinement de structures contractuelles multilingues pour des accords transfrontaliers, avec accent sur la clarté, l'exécutabilité et la cohérence entre différentes juridictions.",
        about_localization_title: "Localisation",
        about_localization_desc: "Adaptation et localisation de documentation juridique, administrative et éditoriale pour des contextes internationaux et nationaux, assurant la précision linguistique et la cohérence culturelle.",
        about_multichannel_operations_title: "Opérations Multicanal",
        about_multichannel_operations_desc: "Coordination de la publication de contenu à travers plusieurs canaux numériques, assurant un déploiement cohérent et des adaptations spécifiques tout en appliquant la localisation multicanal lorsque nécessaire.",
        about_sales_operations_title: "Opérations Commerciales",
        about_sales_operations_desc: "Gestion d'entonnoirs de vente structurés, flux de travail de facturation et communication commerciale directe pour soutenir des transactions sécurisées et une intégration efficace des clients.",
        title_portfolio: "PORTFOLIO",
        title_languages: "LANGUES",
        badge_holding: "Agence Holding",
        grape_desc: "GrapeXagon est une agence holding émergente conçue pour développer et coordonner des plateformes numériques interconnectées, établissant le cadre opérationnel, structurel et stratégique pour des entreprises en ligne évolutives.",
        btn_learn_more: "En savoir plus",
        title_consultancy: "CONSULTATION",
        consultancy_desc: "Vous recherchez une expertise en ingénierie contractuelle, localisation ou automatisation des flux de travail? Proposez un accord:",
        form_company_check: "Entreprise?",
        form_name: "Prénom",
        form_surname: "Nom",
        form_company_name: "Nom de l'entreprise",
        form_email: "E-mail",
        form_phone_check: "Inclure numéro?",
        form_phone: "Numéro de téléphone",
        form_phone_error: "Veuillez entrer un numéro de téléphone valide.",
        form_message: "Proposition",
        form_submit: "Envoyer la proposition",
        form_sending: "Envoi en cours...",
        form_success: "Proposition envoyée avec succès!",
        form_error: "Veuillez remplir tous les champs obligatoires avec des informations valides.",
        form_error_required: "Veuillez remplir tous les champs obligatoires avec des informations valides.",
        form_error_captcha: "Veuillez compléter la vérification reCAPTCHA.",
        footer_phone: "Téléphone",
        footer_email: "E-mail",
        footer_follow: "LinkedIn",
        footer_rights: "par Delta N. Asterling A. F."
    },
    pt: {
        tagline: "PROFISSIONAL MULTIDISCIPLINAR DE IDIOMAS",
        nav_home: "Início",
        nav_about: "Resumo",
        nav_portfolio: "Portfólio",
        nav_consultancy: "Consultoria",
        hero_greeting: "Bem-vindo, eu sou",
        hero_desc: "Especialista multilíngue em contratos e localização com experiência em documentação jurídica internacional, publicação transfronteiriça e coordenação administrativa multilíngue.",
        btn_portfolio: "Portfólio",
        btn_resume: "Currículo",
        title_about: "RESUMO",
        about_administration_title: "Administração",
        about_administration_desc: "Experiência em coordenação administrativa multilíngue, apoio à comunicação transfronteiriça, processos de documentação intermediária e manutenção da consistência terminológica em operações internacionais.",
        about_automation_title: "Automação",
        about_automation_desc: "Design e implementação de sistemas de automação estruturados orientados a reduzir a carga de trabalho manual e melhorar a eficiência em processos administrativos e de documentação em ambientes multilíngues.",
        about_contract_engineering_title: "Engenharia de Contratos",
        about_contract_engineering_desc: "Desenvolvimento e refinamento de estruturas contratuais multilíngues para acordos transfronteiriços, com ênfase na clareza, exequibilidade e consistência entre diferentes jurisdições.",
        about_localization_title: "Localização",
        about_localization_desc: "Adaptação e localização de documentação jurídica, administrativa e editorial para contextos internacionais e nacionais, garantindo precisão linguística e coerência cultural.",
        about_multichannel_operations_title: "Operações Multicanal",
        about_multichannel_operations_desc: "Coordenação da publicação de conteúdo através de múltiplos canais digitais, garantindo implantação consistente e adaptações específicas, aplicando localização multicanal quando necessário.",
        about_sales_operations_title: "Operações de Vendas",
        about_sales_operations_desc: "Gestão de funis de vendas estruturados, fluxos de trabalho de faturação e comunicação direta de vendas para apoiar transações seguras e uma integração eficiente de clientes.",
        title_portfolio: "PORTFÓLIO",
        title_languages: "IDIOMAS",
        badge_holding: "Agência Holding",
        grape_desc: "GrapeXagon é uma agência holding emergente projetada para desenvolver e coordenar plataformas digitais interconectadas, estabelecendo a estrutura operacional, estrutural e estratégica para empreendimentos online escaláveis.",
        btn_learn_more: "Saber Mais",
        title_consultancy: "CONSULTORIA",
        consultancy_desc: "Procura experiência em engenharia de contratos, localização ou automação de fluxos de trabalho? Proponha um acordo:",
        form_company_check: "Empresa?",
        form_name: "Nome",
        form_surname: "Sobrenome",
        form_company_name: "Nome da empresa",
        form_email: "E-mail",
        form_phone_check: "Incluir número?",
        form_phone: "Número de telefone",
        form_phone_error: "Por favor, informe um número de telefone válido.",
        form_message: "Proposta",
        form_submit: "Enviar Proposta",
        form_sending: "Enviando...",
        form_success: "Proposta enviada com sucesso!",
        form_error: "Por favor, preencha todos os campos obrigatórios com informações válidas.",
        form_error_required: "Por favor, preencha todos os campos obrigatórios com informações válidas.",
        form_error_captcha: "Por favor, conclua a verificação reCAPTCHA.",
        footer_phone: "Telefone",
        footer_email: "E-mail",
        footer_follow: "LinkedIn",
        footer_rights: "por Delta N. Asterling A. F."
    },
    de: {
        tagline: "MULTIDISZIPLINÄRER SPRACHPROFI",
        nav_home: "Startseite",
        nav_about: "Zusammenfassung",
        nav_portfolio: "Portfolio",
        nav_consultancy: "Beratung",
        hero_greeting: "Willkommen, ich bin",
        hero_desc: "Mehrsprachiger Spezialist für Verträge und Lokalisierung mit Fachwissen in internationaler juristischer Dokumentation, grenzüberschreitendem Publizieren und mehrsprachiger Verwaltungskoordination.",
        btn_portfolio: "Portfolio",
        btn_resume: "Lebenslauf",
        title_about: "ZUSAMMENFASSUNG",
        about_administration_title: "Verwaltung",
        about_administration_desc: "Erfahrung in mehrsprachiger Verwaltungskoordination, Unterstützung grenzüberschreitender Kommunikation, intermediäre Dokumentationsprozesse und Aufrechterhaltung terminologischer Konsistenz in internationalen Operationen.",
        about_automation_title: "Automatisierung",
        about_automation_desc: "Entwurf und Implementierung strukturierter Automatisierungssysteme zur Reduzierung manueller Arbeitslast und Verbesserung der Effizienz in Verwaltungs- und Dokumentationsprozessen in mehrsprachigen Umgebungen.",
        about_contract_engineering_title: "Vertragsengineering",
        about_contract_engineering_desc: "Entwicklung und Verfeinerung mehrsprachiger Vertragsstrukturen für grenzüberschreitende Vereinbarungen mit Schwerpunkt auf Klarheit, Durchsetzbarkeit und Konsistenz über verschiedene Rechtsordnungen hinweg.",
        about_localization_title: "Lokalisierung",
        about_localization_desc: "Anpassung und Lokalisierung juristischer, administrativer und publizistischer Dokumentation für internationale und nationale Kontexte, unter Sicherstellung linguistischer Genauigkeit und kultureller Kohärenz.",
        about_multichannel_operations_title: "Multikanal-Operationen",
        about_multichannel_operations_desc: "Koordination der Inhaltsveröffentlichung über mehrere digitale Kanäle, unter Sicherstellung konsistenter Bereitstellung und spezifischer Anpassungen unter Anwendung multikanaler Lokalisierung wo erforderlich.",
        about_sales_operations_title: "Vertriebsoperationen",
        about_sales_operations_desc: "Management strukturierter Verkaufstrichter, Rechnungsworkflows und direkter Vertriebskommunikation zur Unterstützung sicherer Transaktionen und effizienter Kundenonboarding.",
        title_portfolio: "PORTFOLIO",
        title_languages: "SPRACHEN",
        badge_holding: "Holding-Agentur",
        grape_desc: "GrapeXagon ist eine aufstrebende Holding-Agentur, die entwickelt wurde, um vernetzte digitale Plattformen zu entwickeln und zu koordinieren und den operativen, strukturellen und strategischen Rahmen für skalierbare Online-Unternehmen zu etablieren.",
        btn_learn_more: "Mehr erfahren",
        title_consultancy: "BERATUNG",
        consultancy_desc: "Suchen Sie Fachwissen in Vertragsengineering, Lokalisierung oder Workflow-Automatisierung? Unterbreiten Sie ein Angebot:",
        form_company_check: "Unternehmen?",
        form_name: "Vorname",
        form_surname: "Nachname",
        form_company_name: "Firmenname",
        form_email: "E-Mail",
        form_phone_check: "Nummer hinzufügen?",
        form_phone: "Telefonnummer",
        form_phone_error: "Bitte geben Sie eine gültige Telefonnummer ein.",
        form_message: "Vorschlag",
        form_submit: "Vorschlag senden",
        form_sending: "Wird gesendet...",
        form_success: "Vorschlag erfolgreich gesendet!",
        form_error: "Bitte füllen Sie alle Pflichtfelder mit gültigen Informationen aus.",
        form_error_required: "Bitte füllen Sie alle Pflichtfelder mit gültigen Informationen aus.",
        form_error_captcha: "Bitte schließen Sie die reCAPTCHA-Verifizierung ab.",
        footer_phone: "Telefon",
        footer_email: "E-Mail",
        footer_follow: "LinkedIn",
        footer_rights: "von Delta N. Asterling A. F."
    },
    ru: {
        tagline: "МНОГОПРОФИЛЬНЫЙ ЯЗЫКОВОЙ СПЕЦИАЛИСТ",
        nav_home: "Главная",
        nav_about: "Резюме",
        nav_portfolio: "Портфолио",
        nav_consultancy: "Консалтинг",
        hero_greeting: "Добро пожаловать, я",
        hero_desc: "Многоязычный специалист по контрактам и локализации с экспертизой в международной юридической документации, трансграничном издательском деле и многоязычной административной координации.",
        btn_portfolio: "Портфолио",
        btn_resume: "Резюме",
        title_about: "РЕЗЮМЕ",
        about_administration_title: "Администрирование",
        about_administration_desc: "Опыт в многоязычной административной координации, поддержка трансграничной коммуникации, посреднические процессы документации и поддержание терминологической согласованности в международных операциях.",
        about_automation_title: "Автоматизация",
        about_automation_desc: "Проектирование и внедрение структурированных систем автоматизации, направленных на сокращение ручной нагрузки и повышение эффективности административных и документационных процессов в многоязычных средах.",
        about_contract_engineering_title: "Контрактный Инжиниринг",
        about_contract_engineering_desc: "Разработка и совершенствование многоязычных контрактных структур для трансграничных соглашений с акцентом на ясность, исполнимость и согласованность в различных юрисдикциях.",
        about_localization_title: "Локализация",
        about_localization_desc: "Адаптация и локализация юридической, административной и издательской документации для международных и национальных контекстов, обеспечивая лингвистическую точность и культурную когерентность.",
        about_multichannel_operations_title: "Мультиканальные Операции",
        about_multichannel_operations_desc: "Координация публикации контента через несколько цифровых каналов, обеспечивая согласованное развертывание и специфические адаптации с применением мультиканальной локализации при необходимости.",
        about_sales_operations_title: "Операции Продаж",
        about_sales_operations_desc: "Управление структурированными воронками продаж, рабочими процессами выставления счетов и прямой коммуникацией продаж для поддержки безопасных транзакций и эффективного онбординга клиентов.",
        title_portfolio: "ПОРТФОЛИО",
        title_languages: "ЯЗЫКИ",
        badge_holding: "Холдинговое агентство",
        grape_desc: "GrapeXagon — это развивающееся холдинговое агентство, разработанное для создания и координации взаимосвязанных цифровых платформ, устанавливающее операционную, структурную и стратегическую рамку для масштабируемых онлайн-предприятий.",
        btn_learn_more: "Узнать больше",
        title_consultancy: "КОНСАЛТИНГ",
        consultancy_desc: "Ищете экспертизу в контрактном инжиниринге, локализации или автоматизации рабочих процессов? Предложите сделку:",
        form_company_check: "Компания?",
        form_name: "Имя",
        form_surname: "Фамилия",
        form_company_name: "Название компании",
        form_email: "Эл. адрес",
        form_phone_check: "Включить номер?",
        form_phone: "Номер телефона",
        form_phone_error: "Пожалуйста, введите корректный номер телефона.",
        form_message: "Предложение",
        form_submit: "Отправить предложение",
        form_sending: "Отправка...",
        form_success: "Предложение успешно отправлено!",
        form_error: "Пожалуйста, заполните все обязательные поля корректной информацией.",
        form_error_required: "Пожалуйста, заполните все обязательные поля корректной информацией.",
        form_error_captcha: "Пожалуйста, пройдите проверку reCAPTCHA.",
        footer_phone: "Телефон",
        footer_email: "Эл. адрес",
        footer_follow: "LinkedIn",
        footer_rights: "от Delta N. Asterling A. F."
    }
};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
}